config/routes.rb
# frozen_string_literal: true

require Rails.root.join("lib", "graphql_playground", "rack")

Rails.application.routes.draw do
  get "/login" => "sessions#new", :as => :login
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy", :as => :logout

  resources :channels, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  namespace :channels do
    resource :directs, only: [:create]
  end

  resources :profiles, only: [:show]

  root "channels#index"

  post "/api/graphql", to: "graphql#execute"
  if Rails.configuration.graphql_playground_enabled
    mount GraphQLPlayground::Rack.new, at: "/graphql"
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  def show
    user = User.find(params[:id])

    render partial: "profiles/profile", locals: {user:}
  end
end

app/views/profiles/_profile.html.erb
<turbo-frame id="profile" class="h-full flex-grow" data-turbo-permanent data-controller="clearer">
  <%- if local_assigns[:user] -%>
    <div class="border-l border-red-100 h-full pl-4" style="min-width: 200px">
      <nav class="flex flex-row justify-between items-baseline mb-5">
        <h2 class="font-bold text-2xl">Profile</h2>
        <div class="text-sm self-center cursor-pointer hover:opacity-75" data-action="click->clearer#clear">╳</div>
      </nav>

      <div class="text-green-900 mb-4">
        @<%= user.username %>
      </div>

      <% if user != current_user %>
        <%= form_tag channels_directs_path, method: :post, class: "mb-4", data: { "turbo-frame" => "_top" } do %>
          <%= hidden_field_tag :user_id, user.id %>
          <%= button_tag "Message", type: "submit", class: "rounded py-2 px-5 border-red-600 border text-red-600 inline-block cursor-pointer hover:bg-red-100 transition-colors disabled:cursor-not-allowed" %>
        <% end %>
      <% end %>
    </div>
  <%- end -%>
</turbo-frame>